language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
- pytest quiz_api_manager
notifications:
  slack:
    rooms:
      - secure: gDJ2nXOOm3vLVCYSEVJYHUq9vXES7afukQHNMFlFyDFq7zwOD/E5KpoVQI2+2Bf7s6lLPoE2QVdCKw6SRzOCe8lVr4Cl9PNZGBVyP6kcQA1mxCwbxPR3DP816BKmbYPOMGZosheBnnbGVsqsEsFAPcw4gM5Z3UQMUv1JDoG3C+gUymkcHNYmXoHwvzLd4qbcBJA2/aucq3k7hwlBkePfduU6SN2B7GM5sfG/mUW4Sy0NGNNCdc4C1sX8mTTRWrK3bmeoFQWCi2RGgTtytiEn2Gz4WC35Fcv3060PL6mHO+dTU3cGeGps0B49kpTr1Qi02QlaPvCSliIPiavKvVNwapMGwSWiQ71M3PRx//KpaawMAojM6gXss2TH+CgKPdZ8mp7soOz6f6suY+7/eltMR+ntm3aiB7ZQKhaliCLzvfTFvWEvZMiJo5CoxIlLHPHBak75erp1a065hItN3r64AF4p0ytBzS3xbcLrCGydccnX79GHfz8pl/Y6Jia6uj6d7rofmwetz9KAyQRN2E2TajPy4IZbksLJqluNzzXKO+miUtjaOhDdXHoKTcO9GtJyfdCk5aTtXHtCwFk3ITcmM36fs4GCtGgJT1lgMtI1Inkdjxk6Dp4I2+jq60TNBBu3OwE0/2uFiZ/yEldu7RFsy0vKwu1r2DeKKzG//L93K/E=