# Generated by Django 3.0.5 on 2020-04-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_auto_20200427_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='Analytic',
        ),
    ]
